---
roles:

  - name: 'geerlingguy.postgresql'

  - name: 'geerlingguy.docker'

  - name: 'geerlingguy.apache'

  - name: 'geerlingguy.php'

collections:

  - name: 'ansible.posix'
    version: '*'

  - name: 'ansible.utils'
    version: '*'

  - name: 'community.crypto'
    version: '*'

  - name: 'community.docker'
    version: '*'

  - name: 'community.general'
    version: '*'

  - name: 'community.libvirt'
    version: '*'

  - name: 'community.mysql'
    version: '*'

  - name: 'community.postgresql'
    version: '*'

  - name: 'community.rabbitmq'
    version: '*'
  
  - name: community.zabbix
    version: '*'

  - name: 'debops.debops'
    version: '*'

  - name: nginxinc.nginx_core
    version: '*'
