---

- name: Mount disks
  vars:
    non_boot_disks: "{{ hostvars[inventory_hostname].diskn | default([]) | rejectattr('id', 'equalto', 1) | list }}"
  when:
    - non_boot_disks | length > 0
    - false # Not ready yet
  ansible.builtin.include_tasks: "mount_disks.yml"
  loop: "{{ non_boot_disks }}"
  loop_control:
    loop_var: item

- name: Creating Users
  loop: "{{ user_defs }}"
  when: user_defs is defined and user_defs | length > 0
  ansible.builtin.include_tasks: "create_linux_user.yml"

- name: Installing packages
  ansible.builtin.package:
    name: '{{ pkgs }}'
    state: present
