---

- name: "Dockers: Configure docker.nikssk.id.lv"
  hosts: docker0.nikssk.id.lv
  gather_facts: true
  roles:
    - role: niksskersts.ansible-role-vm
      pkgs: '{{ base_pkgs }}'

    - role: niksskersts.ansible-role-docker
      wipe: false
      pull_policy: always

    - role: niksskersts.ansible-role-caddy
      get_cert_cloudflare: false
      domain: '{{ cloudflare.cloud_domain }}'
      cloudflare_token: '{{ cloudflare.token }}'
      certbot_email: '{{ smtp.username }}'
      cert_path: '{{ caddy.cert_path }}'
      caddy_user: '{{ caddy.user }}'
      caddy_group: '{{ caddy.user }}'
      caddy_config_path: '{{ caddy.config_path }}'
      caddy_config_tls: '{{ caddy.tls }}'
      caddy_defs: '{{ docker_defs }}'
      backend_cert_defs:
        - bitwarden:
          dest: '{{ bitwarden.backend_cert_path }}'
          content: '{{ bitwarden.backend_cert }}'
          mode: '650'
