---

- name: Configure Proxmox host
  hosts: qianbei.nikssk.id.lv
  gather_facts: true
  roles:
    - role: niksskersts.ansible-proxmox-server
      template: "https://cloud.debian.org/images/cloud/bookworm/20250115-1993/debian-12-generic-amd64-20250115-1993.tar.xz"
      template_destination_path: /var/lib/vz/template/qemu
      template_sha512: sha512:065a56184ecbddd583283ca854a274a17765d7ba1ff27cd34851eb9be9769c701e9db0e35c44480a080ff02ad2111ee1377a1e10458bcd63f2909a504c1a6d58
      def_pool: 'tpool'
      vm_group: 'vm'
  tasks:

    - name: End play
      ansible.builtin.meta: end_play
