---

- name: Configure Proxmox host
  hosts: qianbei.nikssk.id.lv
  gather_facts: true
  roles:
    - role: server
      vm_group: 'qianbei_vm'
      lxc_group: 'qianbei_lxc'

  tasks:

    - name: End play
      ansible.builtin.meta: end_play
