---

- name: Configure Proxmox host
  hosts: qianbei.nikssk.id.lv
  gather_facts: true
  collections:
    - niksskersts.proxmox
  roles:
    - role: niksskersts.proxmox.server
      vm_group: 'qianbei_vm'

  tasks:

    - name: End play
      ansible.builtin.meta: end_play
