---

- name: "Dockers: Configure docker.nikssk.id.lv"
  hosts: shushi.nikssk.id.lv
  gather_facts: true
  roles:
    - role: niksskersts.ansible-role-vm
    - role: niksskersts.ansible-role-docker
    - role: niksskersts.ansible-role-nfs-server
  tasks:

    - name: Deploy software
      ansible.builtin.apt:
        name:
          - cockpit
          - screenfetch
