---

# Update all
- name: update_all
  ansible.builtin.import_playbook: all.yml

# Configure Servers

- name: qianbei.nikssk.id.lv.yml
  ansible.builtin.import_playbook: qianbei.nikssk.id.lv.yml

- name: shushi.nikssk.id.lv.yml
  ansible.builtin.import_playbook: shushi.nikssk.id.lv.yml

- name: tan.nikssk.id.lv.yml
  ansible.builtin.import_playbook: tan.nikssk.id.lv.yml

# Configure DB

- name: db.nikssk.id.lv.yml
  ansible.builtin.import_playbook: db.nikssk.id.lv.yml

# Configure Monitoring server

- name: monitor.nikssk.id.lv.yml
  ansible.builtin.import_playbook: monitor.nikssk.id.lv.yml

# Configure Dockers

- name: docker0.nikssk.id.lv.yml
  ansible.builtin.import_playbook: docker0.nikssk.id.lv.yml

- name: docker1.nikssk.id.lv.yml
  ansible.builtin.import_playbook: docker1.nikssk.id.lv.yml